### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by rektpartyaftermath** [renehorstmann/Pixelc#1]
# Problem
The app doesn't start, it just show a black screen and stuck there for eternity.
## My Device
Oppo A37F with Android 5.1

**Comment by renehorstmann** [comment]
Hey,
do you use the Android App from the PlayStore or the web app and if so, which Browser are you using?
Normally my engine should spot unsupported devices and display an error info.

**Comment by renehorstmann** [comment]
horsimann.de/pixelc/debug
shows the console output of the app. Could you test that, too?

**Comment by rektpartyaftermath** [comment]
Yes, i'm using android version from PlayStore.

**Comment by rektpartyaftermath** [comment]
i'm also try to use the WebApp version, but it say unsupported browser.

**Comment by renehorstmann** [comment]
I suspect that it is due to the OpenGLES version. I actually thought the app would work with GLES3.0, but apparently it doesn't. I'm sorry it doesn't work on your device.

**Comment by rektpartyaftermath** [comment]
Okay then, no problem.

**Comment by renehorstmann** [comment]
Dont know why, but it seems that your old Android 5.1 Version may be the problem. Other users with newer Android Versions and OpenGLES3.0 dont have that problem.
I will update the minimal Android Version to Android 6.0 in the future, sorry that it doesnt help you.
