### ISSUE TITLE
Provide an apk

### ISSUE THREAD

**Issue by therealbluepandabear** [renehorstmann/Pixelc#2]
Title.

**Comment by renehorstmann** [comment]
Whats wrong with the Google Play Store?

**Comment by therealbluepandabear** [comment]
> Whats wrong with the Google Play Store?

Hey,

It's proprietary malware that steals user data. I have a degoogled phone without the Play Store so I am unable to try your app without an APK.

**Comment by renehorstmann** [comment]
Maybe I add a port to F-Droid later, seems to be a lot of work and I dont have that time in the moment, also the IOS Version will go first.
If you just want to test (or use) my Pixelc App, open the WebApp. Its the same thing as the Android apk.
You can also add a shortcut of the WebApp to your home screen from your Browser to get a fullscreen app experience.
(Just the maximal gpu texture sizes will be lower, which results in a lowered maximal tilemap size you can use in the tile mode)

**Comment by therealbluepandabear** [comment]
No worries. Your app; your decision. 

Good luck!
